return {
  -- "edluffy/hologram.nvim",
  -- event = "VeryLazy",
  -- config = function()
  --   require("hologram").setup({
  --     auto_display = true,
  --     -- Add these lines:
  --     render = {
  --       min_padding = 5,
  --       show_label = true,
  --       use_dither = true,
  --       foreground_color = false,
  --       background_color = false,
  --     },
  --     -- If you're on Neovim 0.8+, enable this
  --     -- window_float = {
  --     --   blend = 0
  --     -- }
  --   })
  -- end,
}
